### ISSUE TITLE
where is the paper?

### ISSUE THREAD

**Issue by tanshuai0219** [yuangan/EAT_code#1]

**Comment by yuangan** [comment]
I sincerely apologize for the delay in publishing our paper. I have submitted it to arXiv, and it will be accessible shortly, perhaps as soon as tomorrow.

**Comment by tanshuai0219** [comment]
> 

Thanks for your reply! Congratulations！

**Comment by yuangan** [comment]
Thank you! Our paper is available now: http://arxiv.org/abs/2309.04946
