### ISSUE TITLE
能否提供“评价指标”的量化代码

### ISSUE THREAD

**Issue by laura990501** [yuangan/EAT_code#11]
作者您好！非常感谢您能公开“Efficient Emotional Adaptation for Audio-Driven Talking-Head Generation ”的相关代码！
请问您能否提供 “PSNR M/F-LMD Sync Accemo” 这四个指标的量化代码。

**Comment by yuangan** [comment]
你好，我已经开源了量化比较的代码，请参考这个[Repo](https://github.com/yuangan/evaluation_eat)
