### ISSUE TITLE
How to change a new image as input?

### ISSUE THREAD

**Issue by piwawa** [yuangan/EAT_code#12]
![image](https://github.com/yuangan/EAT_code/assets/46926496/82b931b3-0830-49f5-ad3f-1d2e7b5c6397)

This note indicated to put images in `./demo/imgs/`, but the default file tree is like this:
![image](https://github.com/yuangan/EAT_code/assets/46926496/83af3e3a-65fe-4de0-9d14-d294143ef9dc)

Q1: What image name should i set? 

Q2: How to specify the source image when i run `python demo.py`?

Q3: How is the generated talking head video driven?

**Comment by yuangan** [comment]
Hi, for further details, you can refer to our code. Here are the answers to your questions:

A1: You have the flexibility to choose any name you prefer. This name will be used in the output filename, which can be found at ./demo/output/deepprompt_eam3d_all_final_313/[your chosen image name]_xxxx.mp4.

A2: To use images in the process, simply place the desired images in `./demo/imgs`. The demo.py script will automatically generate videos using all the images in these folders. If you wish to specify certain image names, you will need to modify the corresponding line in demo.py, which is located here: [demo.py](https://github.com/yuangan/EAT_code/blob/main/demo.py#L332)

A3: The poses and audio used in the videos are sourced from the processed video. The video folder is designated by the `--root_wav` parameter.
