### ISSUE TITLE
请问所有的代码都已经开源了吗

### ISSUE THREAD

**Issue by Wangman1** [yuangan/EAT_code#13]
作者您好，感谢您优秀的工作，看到您昨天进行了项目更新，请问目前训练和推理相关的所有代码都开源了吗，谢谢~

**Comment by yuangan** [comment]
是的，基本都开源了，关于Face-vid2vid部分的训练，可以参考我们的论文和这个[repo](https://github.com/zhanglonghao1992/One-Shot_Free-View_Neural_Talking_Head_Synthesis)。暂时不会有大的更新了。
