### ISSUE TITLE
关于voxs_images和voxs_wavs

### ISSUE THREAD

**Issue by Tpcsy** [yuangan/EAT_code#14]
作者您好，您的项目非常棒，我很感兴趣，但是为在进行A2KP Training时遇到了一些问题，当我执行python pretrain_a2kp.py --config config/pretrain_a2kp_s1.yaml --device_ids 0,1,2,3 --checkpoint ./ckpt/pretrain_new_274.pth.tar时，终端循环输出如下：
/Vox2-mp4/dev//voxs_images/id00062_osRcP9DYjAQ_00416 59878 /Vox2-mp4/dev//voxs_wavs/id00062_osRcP9DYjAQ_00416.wav
/Vox2-mp4/dev//voxs_images/id00776_f4QpbV2nV14_00184 3282 /Vox2-mp4/dev//voxs_wavs/id00776_f4QpbV2nV14_00184.wav
/Vox2-mp4/dev//voxs_images/id00287_DJpelTdmYdk_00039 83446 /Vox2-mp4/dev//voxs_wavs/id00287_DJpelTdmYdk_00039.wav
我判断是没有找到voxs_images和voxs_wavs文件夹，我下载了vox数据集，里面没有voxs_images和voxs_wavs，请问是否是需要对vox数据集进行预处理，我没有找到数据集的预处理代码。谢谢！

**Comment by yuangan** [comment]
感谢关注，voxceleb是需要预处理的，你可以参考[这里](https://github.com/yuangan/EAT_code/tree/main#preprocessing)进行对视频数据进行预处理。需要注意的是，训练集不需要[这一行](https://github.com/yuangan/EAT_code/blob/main/preprocess/preprocess_video.py#L40C23-L40C45)后面针对demo的处理。得到voxs_images之后，你还需要利用extract_bbox提取人脸的boundingbox。有其他关于训练的问题可以随时提issue。

**Comment by Tpcsy** [comment]
自动回复：您好，邮件已收到
