### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by YZX-codesky** [yuangan/EAT_code#15]
您好，作者，非常感谢您的工作！我在训练第二阶段的代码的时候，发现训练的时间变得非常长，长达800多个小时，见下图：
![训练截图](https://github.com/yuangan/EAT_code/assets/103978463/b67d31f9-1f5a-4629-950e-ba17c9fd66a8)
我采用的是一张3090显卡。想问一下这个是正常的吗？

**Comment by yuangan** [comment]
我们用了4张3090卡训练，按半个小时存一个epoch，一般来说第二阶段训练5-8个小时就行，具体训练时间和performance的关系可以参考我们论文中的Fig.5。1张3090可能需要训久一点，你可以根据训练loss和其他指标来判断需要训练多久。

**Comment by YZX-codesky** [comment]
> 我们用了4张3090卡训练，按半个小时存一个epoch，一般来说第二阶段训练5-8个小时就行，具体训练时间和performance的关系可以参考我们论文中的Fig.5。1张3090可能需要训久一点，你可以根据训练loss和其他指标来判断需要训练多久。
想问一下训练5-8个小时，是训练多少个epochs，是文章中的2000个吗？
![image](https://github.com/yuangan/EAT_code/assets/103978463/8e034be6-253f-46b0-ab74-f54df33dab9b)

**Comment by YZX-codesky** [comment]
想问一下训练5-8个小时，是训练多少个epochs，是文件中的2000个吗？还是根据损失的收敛情况做了调整








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuangan/EAT_code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月8日(星期一) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuangan/EAT_code] 训练时间 (Issue #15)





 
我们用了4张3090卡训练，按半个小时存一个epoch，一般来说第二阶段训练5-8个小时就行，具体训练时间和performance的关系可以参考我们论文中的Fig.5。1张3090可能需要训久一点，你可以根据训练loss和其他指标来判断需要训练多久。
