### ISSUE TITLE
MEAD test list

### ISSUE THREAD

**Issue by chaolongy** [yuangan/EAT_code#17]
MEAD PartA has 48 identities. In your experiments, could you please provide your test list? Thanks!

**Comment by yuangan** [comment]
Thank you for your attention. We tested MEAD on 2 males and 2 females: M003, M030, W009, W015. You can find them [here](https://drive.google.com/file/d/1_6OfvP1B5zApXq7AIQm68PZu1kNyMwUY/view?usp=drive_link)
