### ISSUE TITLE
Custom Video - Preprocess code

### ISSUE THREAD

**Issue by oijoijcoiejoijce** [yuangan/EAT_code#3]
Thanks for the great work - could you pelase clarify how to process custom videos?

**Comment by skeletonNN** [comment]
Hello, Can you share the preprocess code?

**Comment by yuangan** [comment]
Yes, I'm actively cleaning and testing these codes. Please allow me one more day and thank you for your patience.

**Comment by yuangan** [comment]
Hi, I have updated the preprocessing code. Thank you for your support.
