### ISSUE TITLE
FileNotFoundError: Package has no location <module 'imageio_ffmpeg.binaries' (namespace)>

### ISSUE THREAD

**Issue by Mariosz2** [yuangan/EAT_code#31]
This happens when I run `demo.py`, which is configured according to `mamba env create -f environment.yml`. The final solution is to simply return 'imagi-ffmpeg' to version '0.4.9' using 'mamba install imageio-ffmpeg=0.4.9'. This could be because the latest version of 'imagi-ffmpeg 0.5.0', released on June 1st, does not contain `imageio_ffmpeg.binaries`.

**Comment by yuangan** [comment]
Thank you for your reminder. I have modified the `environment.yml` file.

**Comment by Mariosz2** [comment]
Thank you :)
