### ISSUE TITLE
Fail to get output from demo.py

### ISSUE THREAD

**Issue by andysummer0715** [yuangan/EAT_code#38]
Dear Sir/Madam,
I appreciate your work so much. However, I encountered problem that I installed all the packages need, I ran demo.py silky, but when I opened output_dir, only found log file, video is not included.
What I can do?
Best Wishes.

**Comment by yuangan** [comment]
Hi, thank you for your attention. 
Do you have any output logs? We can locate the problem together. Or you can try it in [Colab](https://colab.research.google.com/drive/133hwDHzsfRYl-nQCUQxJGjcXa5Fae22Z#scrollTo=GWqHlw6kKrbo).
Best Wishes~

**Comment by andysummer0715** [comment]
Solved. Thank you for your awesome work！
