### ISSUE TITLE
About training code

### ISSUE THREAD

**Issue by HJHGJGHHG** [yuangan/EAT_code#4]
Thank you for your excellent work. We want to train the network based on our own datasets. Any plan to upload the training code?

**Comment by yuangan** [comment]
Thank you for your attention.  Cleaning up and releasing the code for such a project in a short time is challenging. If you wish to use our training code in your work, please don't hesitate to contact me at [ganyuan@zju.edu.cn](mailto:ganyuan@zju.edu.cn) or add me on WeChat: kuraudogan. We plan to release part of the training code for research purposes only.
