### ISSUE TITLE
The training code

### ISSUE THREAD

**Issue by julia-cherry** [yuangan/EAT_code#7]
When will you release the training code? Thanks very much!

**Comment by yuangan** [comment]
Thank you for your attention. We have been busy recently. The training code may be released in the next month.

**Comment by yuangan** [comment]
We have released the Emotional Adaptation Training code. Thank you for your patience~

**Comment by YZX-codesky** [comment]
When will the complete training code containing two stages be released? Thank you very much！

**Comment by yuangan** [comment]
Thank you for your attention. We will release the A2ET training code next month, which will require several days to train with VoxCeleb2.

**Comment by yuangan** [comment]
We have now released all of the training code. If you have any questions about the training, please feel free to ask me.

**Comment by YZX-codesky** [comment]
您好，作者，非常感谢您的工作！我在训练第二阶段的代码的时候，发现训练的时间变得非常长，长达800多个小时，见下图：

我采用的是一张3090显卡，batch_size也改为了1。想问一下这个是正常的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuangan/EAT_code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuangan/EAT_code] The training code (Issue #7)





 
Closed #7 as completed.

**Comment by yuangan** [comment]
我们用了4张3090卡训练，按半个小时存一个epoch，一般来说第二阶段训练5-8个小时就行，具体训练时间和performance的关系可以参考我们论文中的Fig.5。1张3090可能需要训久一点，你可以根据训练loss和其他指标来判断需要训练多久。
